name: Deploy to EC2
name: Deploy to EC2

on:
  push:
    branches:
      - deploy
      - deploy

jobs:
  deploy:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > Wisdom_wars.pem
        chmod 600 Wisdom_wars.pem
        scp -i Wisdom_wars.pem -r ./build ec2-user@$ip-172-31-20-192.eu-west-2.compute.internal:/home/ec2-user/var/www/quizapp
        ssh -i Wisdom_wars.pem ec2-user@$ip-172-31-20-192.eu-west-2.compute.internal 'cd /home/ec2-user/var/www/quizapp && npm install && npm start'



  
